#!/usr/bin/env python3
"""Build B0 Step4 summary artifacts from existing Step3 outputs."""

from __future__ import annotations

import csv
import os
from pathlib import Path


METRIC_KEYS = ["image_AUROC", "image_F1Score", "pixel_AUROC", "pixel_F1Score"]


def _require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required env var: {name}")
    return value


def _read_metrics(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            metric = (row.get("metric") or "").strip()
            value = (row.get("value") or "").strip()
            if metric:
                data[metric] = value
    return data


def _na(value: str) -> str:
    return value if value else "NA"


def _build_rows(run_dir: Path, seed: str) -> list[dict[str, str]]:
    datasets = ["RESC", "OCT2017"]
    rows: list[dict[str, str]] = []

    for dataset in datasets:
        metrics_path = run_dir / "06_outputs" / "metrics" / f"metrics__B0__{dataset}__seed{seed}.csv"
        ckpt_path = run_dir / "06_outputs" / "checkpoints" / f"model__B0__{dataset}__seed{seed}.ckpt"
        train_log = run_dir / "05_logs" / "train" / f"train__B0__{dataset}__gbr_ad.txt"
        test_log = run_dir / "05_logs" / "test" / f"test__B0__{dataset}__gbr_ad.txt"

        metrics_map = _read_metrics(metrics_path)
        row = {
            "dataset": dataset,
            "seed": seed,
            "image_AUROC": metrics_map.get("image_AUROC", ""),
            "image_F1Score": metrics_map.get("image_F1Score", ""),
            "pixel_AUROC": metrics_map.get("pixel_AUROC", ""),
            "pixel_F1Score": metrics_map.get("pixel_F1Score", ""),
            "ckpt_path": str(ckpt_path.resolve()),
            "metrics_path": str(metrics_path.resolve()),
            "train_log_path": str(train_log.resolve()),
            "test_log_path": str(test_log.resolve()),
            "run_dir": str(run_dir.resolve()),
        }
        rows.append(row)
    return rows


def _write_summary_csv(path: Path, rows: list[dict[str, str]]) -> None:
    fields = [
        "dataset",
        "seed",
        "image_AUROC",
        "image_F1Score",
        "pixel_AUROC",
        "pixel_F1Score",
        "ckpt_path",
        "metrics_path",
        "train_log_path",
        "test_log_path",
        "run_dir",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _write_latex(path: Path, rows: list[dict[str, str]]) -> None:
    lines: list[str] = []
    lines.append("% Auto-generated by step4__b0_summarize.py")
    lines.append("\\begin{table}[htbp]")
    lines.append("\\centering")
    lines.append("\\caption{B0 Debug Metrics (Seed 42)}")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("Dataset & image\\_AUROC & image\\_F1 & pixel\\_AUROC & pixel\\_F1 \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(
            f"{r['dataset']} & {_na(r['image_AUROC'])} & {_na(r['image_F1Score'])} & "
            f"{_na(r['pixel_AUROC'])} & {_na(r['pixel_F1Score'])} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    lines.append("\\begin{table}[htbp]")
    lines.append("\\centering")
    lines.append("\\caption{B0 Artifacts (Absolute Paths)}")
    lines.append("\\begin{tabular}{ll}")
    lines.append("\\toprule")
    lines.append("Item & Path \\\\")
    lines.append("\\midrule")
    for r in rows:
        d = r["dataset"]
        lines.append(f"{d} checkpoint & \\path{{{r['ckpt_path']}}} \\\\")
        lines.append(f"{d} metrics & \\path{{{r['metrics_path']}}} \\\\")
        lines.append(f"{d} train log & \\path{{{r['train_log_path']}}} \\\\")
        lines.append(f"{d} test log & \\path{{{r['test_log_path']}}} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_repro(path: Path, run_dir: Path, rows: list[dict[str, str]], seed: str) -> None:
    env_dir = run_dir / "01_env"
    lines: list[str] = []
    lines.append("# Reproducibility Checklist: B0 Seed 42")
    lines.append("")
    lines.append("- [x] Run directory:")
    lines.append(f"  - `{run_dir.resolve()}`")
    lines.append("- [x] Environment snapshot paths (if present):")
    if env_dir.exists():
        for p in sorted(env_dir.iterdir()):
            lines.append(f"  - `{p.resolve()}`")
    else:
        lines.append("  - `01_env` not found")
    lines.append("- [x] Commands to regenerate environment snapshots:")
    lines.append("  - `conda env export -n gbessay_resc_rd4ad_cpu > 01_env/conda_env_export.yaml`")
    lines.append("  - `python -V > 01_env/python_version.txt`")
    lines.append("  - `pip freeze > 01_env/pip_freeze.txt`")
    lines.append("- [x] Config paths used:")
    lines.append(f"  - `{(run_dir / '04_configs' / 'RESC__GBR-AD__B0_debug.yaml').resolve()}`")
    lines.append(f"  - `{(run_dir / '04_configs' / 'OCT2017__GBR-AD__B0_debug.yaml').resolve()}`")
    lines.append("- [x] Scripts used:")
    lines.append(f"  - `{(run_dir / '00_admin' / 'cmd' / 'step2__b0_prepare.sh').resolve()}`")
    lines.append(f"  - `{(run_dir / '00_admin' / 'cmd' / 'step2__make_configs.py').resolve()}`")
    lines.append(f"  - `{(run_dir / '00_admin' / 'cmd' / 'step3__b0_run.sh').resolve()}`")
    lines.append("- [x] Log paths:")
    for r in rows:
        lines.append(f"  - `{r['train_log_path']}`")
        lines.append(f"  - `{r['test_log_path']}`")
    lines.append(f"  - `{(run_dir / '05_logs' / 'step3__B0__run_all.txt').resolve()}`")
    lines.append("- [x] Output paths:")
    for r in rows:
        lines.append(f"  - `{r['ckpt_path']}`")
        lines.append(f"  - `{r['metrics_path']}`")
    lines.append(f"  - `{(run_dir / '06_outputs' / 'metrics' / f'summary__B0__seed{seed}.csv').resolve()}`")
    lines.append("- [x] Exact commands to rerun Step3:")
    lines.append(f"  - `export RUN_DIR='{run_dir.resolve()}'`")
    lines.append("  - `export BMAD_DIR=\"$RUN_DIR/02_src/BMAD\"`")
    lines.append(f"  - `export SEED={seed}`")
    lines.append("  - `bash \"$RUN_DIR/00_admin/cmd/step3__b0_run.sh\" | tee \"$RUN_DIR/05_logs/step3__B0__run_all.txt\"`")
    lines.append("- [x] Note:")
    lines.append("  - `num_workers` was forced to `0` in B0 configs due macOS shared-memory restrictions (`torch_shm_manager` permission issue).")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    run_dir = Path(_require_env("RUN_DIR")).resolve()
    seed = os.environ.get("SEED", "42").strip() or "42"
    out_dir = run_dir / "00_admin" / "step4"
    out_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "06_outputs" / "metrics").mkdir(parents=True, exist_ok=True)

    rows = _build_rows(run_dir, seed)
    summary_csv = run_dir / "06_outputs" / "metrics" / f"summary__B0__seed{seed}.csv"
    latex_tex = out_dir / f"latex_table__B0__seed{seed}.tex"
    repro_md = out_dir / f"repro_checklist__B0__seed{seed}.md"

    _write_summary_csv(summary_csv, rows)
    _write_latex(latex_tex, rows)
    _write_repro(repro_md, run_dir, rows, seed)

    produced = [summary_csv, latex_tex, repro_md]
    print("Produced files:")
    for p in produced:
        size = p.stat().st_size if p.exists() else -1
        print(f"- {p} ({size} bytes)")

    print("\nSummary table head:")
    with summary_csv.open("r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            print(line.rstrip("\n"))
            if idx >= 3:
                break

    print("\nLaTeX metrics table:")
    in_metrics = False
    for line in latex_tex.read_text(encoding="utf-8").splitlines():
        if line.strip() == "\\begin{tabular}{lcccc}":
            in_metrics = True
        if in_metrics:
            print(line)
            if line.strip() == "\\end{tabular}":
                break

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
